[workspace]
publish = false
release = true
git_release_enable = true
git_tag_enable = true
release_always = false
changelog_update = true

[changelog]
header = """\
# Changelog

All notable changes to this project are documented here.

"""
