[workspace]
publish = false
release = true
git_release_enable = false
git_tag_enable = true
release_always = true
changelog_update = true

[changelog]
header = """\
# Changelog

All notable changes to this project are documented here.

"""

[[package]]
name = "phoxal-cli"
release = true
