[package]
name = "phoxal-cli-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
console = "0.15.11"
derive-new = { workspace = true }
derive_setters = { workspace = true }
hex = { workspace = true }
phoxal-bus = { workspace = true }
phoxal-component-api = { workspace = true }
phoxal-runtime-localize-api = { workspace = true }
phoxal-utils-component = { workspace = true }
phoxal-utils-conventions = { workspace = true }
phoxal-utils-robot = { workspace = true }
phoxal-engine = { workspace = true }
phoxal-utils-simulation = { workspace = true }
phoxal-utils-structure = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
phoxal-simulator-api = { workspace = true }
urdf-rs = { workspace = true }

[lints]
workspace = true
