[package]
name = "phoxal-cli-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
console = { workspace = true }
phoxal-cli-core = { workspace = true }
phoxal-cli-observation = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }
tuirealm = { workspace = true }
tui-realm-stdlib = { workspace = true }

[lints]
workspace = true
