[package]
name = "phoxal-cli-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
console = { workspace = true }
phoxal-cli-core = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
crossterm = { workspace = true }
unicode-width = { workspace = true }

[lints]
workspace = true
