use std::fs;

use anyhow::Context;
use phoxal_cli::resolver::host_target_triple;
use phoxal_cli::simulation::{SimulateOptions, prepare};
use phoxal_cli_core::project::suite::{
    fixture_simulator_entry_for_tests, fixture_suite_for_tests, fixture_tool_entry_for_tests,
};

#[test]
fn simulate_dry_run_resolves_without_writing_local_launch_directories() -> anyhow::Result<()> {
    let temp = tempfile::tempdir()?;
    write_robot_project(temp.path())?;
    let suite_path = write_suite(temp.path())?;
    write_vendored_fixture_binaries(temp.path(), &suite_path)?;

    let plan = prepare(
        temp.path(),
        SimulateOptions {
            world: "test".to_string(),
            suite_source: Some(suite_path.display().to_string()),
            ..SimulateOptions::default()
        },
    )?;

    assert!(!temp.path().join(".phoxal/run").exists());
    assert!(!temp.path().join(".phoxal/webots").exists());
    assert!(!temp.path().join("phoxal.sources.lock").exists());
    // `LaunchMode::Webots` carries the resolved world path directly now
    // (there is no separate `world_path` field to check against).
    match &plan.plan.mode {
        phoxal_cli_core::project::launch_plan::LaunchMode::Webots { world } => {
            assert_eq!(*world, temp.path().join("worlds/test.wbt"));
        }
        other => panic!("expected LaunchMode::Webots, got {other:?}"),
    }
    // Every resolved tool is now a required robot participant. The router
    // remains the separately supervised graph root.
    assert_eq!(
        plan.plan.robots[0]
            .participants
            .iter()
            .filter_map(|participant| match participant.execution {
                phoxal_cli_core::project::launch_plan::ParticipantExecution::OfficialTool {
                    ..
                } => Some(participant.launch.participant_id.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>(),
        vec![
            "tool-bus-testbot",
            "tool-device-testbot",
            "tool-joypad-testbot",
            "tool-log-testbot",
            "tool-telemetry-testbot",
        ]
    );
    assert_eq!(
        plan.ctx.source().unwrap().resolved.platform_runtimes.len(),
        0
    );

    Ok(())
}

fn write_vendored_fixture_binaries(
    root: &std::path::Path,
    suite_path: &std::path::Path,
) -> anyhow::Result<()> {
    // `prepare` is called directly rather than through AppContext in this
    // integration test, so point project-local path helpers at its fixture.
    unsafe { std::env::set_var(phoxal_cli::host_paths::PROJECT_ROOT_ENV, root) };
    let source = std::env::current_exe()?;
    let target = host_target_triple();
    let suite = phoxal_cli_core::project::suite::read_suite_path(suite_path)?;
    for artifact in &suite.artifacts {
        let package = artifact.id.as_str();
        let binary = package.replace('/', "-");
        let (provider, package_name) = package
            .split_once('/')
            .context("fixture package must be provider-qualified")?;
        let package_dir = root
            .join(".phoxal/artifacts")
            .join(provider)
            .join(package_name);
        let version_dir = package_dir
            .join(format!("versions/{}/targets", suite.version))
            .join(&target);
        fs::create_dir_all(&version_dir)?;
        fs::copy(&source, version_dir.join(binary))?;
        fs::write(version_dir.join(".phoxal-sha256"), "0".repeat(64))?;
        #[cfg(unix)]
        std::os::unix::fs::symlink(
            format!("versions/{}", suite.version),
            package_dir.join("active"),
        )?;
        #[cfg(windows)]
        std::os::windows::fs::symlink_dir(
            format!("versions/{}", suite.version),
            package_dir.join("active"),
        )?;
    }
    Ok(())
}

fn write_robot_project(root: &std::path::Path) -> anyhow::Result<()> {
    fs::create_dir_all(root.join("src"))?;
    fs::write(
        root.join("Cargo.toml"),
        r#"[package]
name = "testbot-train-anchor"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]
members = []
exclude = ["train/phoxal"]
resolver = "3"

[dependencies]
phoxal = { version = "=0.1.0", path = "train/phoxal" }
"#,
    )?;
    fs::write(root.join("src/lib.rs"), "")?;
    fs::create_dir_all(root.join("train/phoxal/src"))?;
    fs::write(
        root.join("train/phoxal/Cargo.toml"),
        r#"[package]
name = "phoxal"
version = "0.1.0"
edition = "2024"
"#,
    )?;
    fs::write(root.join("train/phoxal/src/lib.rs"), "")?;
    fs::write(
        root.join("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "phoxal"
version = "0.1.0"

[[package]]
name = "testbot-train-anchor"
version = "0.0.0"
dependencies = [
 "phoxal",
]
"#,
    )?;
    fs::write(root.join("robot.yaml"), minimal_robot_yaml())?;
    fs::write(
        root.join("structure.urdf"),
        r#"<robot name="testbot"><link name="base_footprint"/><link name="base_link"/><joint name="base_joint" type="fixed"><parent link="base_footprint"/><child link="base_link"/></joint></robot>"#,
    )?;
    fs::create_dir_all(root.join("worlds"))?;
    fs::write(
        root.join("worlds/test.wbt"),
        "#VRML_SIM R2023b utf8\n\nWorldInfo {\n}\n",
    )?;
    Ok(())
}

fn minimal_robot_yaml() -> &'static str {
    r#"schema: robot/v0

robot:
  id: testbot
  namespace: test
  motion_limits:
    max_linear_speed_mps: 0.6
    max_angular_speed_radps: 2.0
  structure: structure.urdf
  kinematic:
    kind: differential
    left_actuators: [left_drive.motor]
    right_actuators: [right_drive.motor]
    left_encoders: [left_drive.encoder]
    right_encoders: [right_drive.encoder]
    wheel_radius_m: 0.1
    wheel_base_m: 0.5
  components: {}

"#
}

fn write_suite(root: &std::path::Path) -> anyhow::Result<std::path::PathBuf> {
    let path = root.join("suite.json");
    let suite = fixture_suite_for_tests(vec![
        fixture_tool_entry_for_tests("router", "0.1.0", &host_target_triple(), true, Vec::new()),
        fixture_tool_entry_for_tests("joypad", "0.1.0", &host_target_triple(), true, Vec::new()),
        fixture_tool_entry_for_tests("bus", "0.1.0", &host_target_triple(), true, Vec::new()),
        fixture_tool_entry_for_tests("device", "0.1.0", &host_target_triple(), true, Vec::new()),
        fixture_tool_entry_for_tests("log", "0.1.0", &host_target_triple(), true, Vec::new()),
        fixture_tool_entry_for_tests(
            "telemetry",
            "0.1.0",
            &host_target_triple(),
            true,
            Vec::new(),
        ),
        fixture_simulator_entry_for_tests(
            "webots-supervisor",
            "0.1.0",
            &host_target_triple(),
            true,
            Vec::new(),
        ),
        fixture_simulator_entry_for_tests(
            "webots-controller",
            "0.1.0",
            &host_target_triple(),
            true,
            Vec::new(),
        ),
    ]);
    fs::write(&path, serde_json::to_string_pretty(&suite)?)?;
    Ok(path)
}
