[package]
name = "phoxal-cli-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
phoxal-cli-core = { workspace = true }
phoxal-cli-protocol = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "sync", "time"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[lints]
workspace = true
