//! Generates and resolves `.phoxal/resolve/Cargo.toml`.
//!
//! `cargo install` cannot materialize a package with no binary target, and
//! Cargo silently drops a dependency on a package with no library target from
//! the resolve graph (organization#951 WS4: "ignoring invalid dependency ...
//! which is missing a lib target"). Asset-carrying official component
//! packages therefore ship an anchor `src/lib.rs`, and the CLI resolves their
//! on-disk extraction directory by depending on them from a private,
//! generated package and reading `cargo metadata` back - the only way to ask
//! Cargo "where did you put this" for a package with no executable to run.
//!
//! `robot.yaml` stays the single source of truth: official components are
//! never declared in the robot's own `Cargo.toml`. This generated manifest is
//! purely a resolution instrument, rewritten on every resolve.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use serde::Deserialize;

use super::catalog::{cargo_package_name, registry_config_arg};

/// `.phoxal/resolve/` relative to the robot project root.
pub const RESOLVE_MANIFEST_DIR_RELATIVE: &str = ".phoxal/resolve";

/// One official component package the generated manifest depends on.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComponentDependency {
    /// The catalog package id (`phoxal/component-ddsm115`).
    pub catalog_id: String,
    /// The exact framework train version every official package pins to.
    pub train: String,
}

/// Write `.phoxal/resolve/Cargo.toml` and its anchor `src/lib.rs` under
/// `project_root`, with one dependency per distinct `dependencies` entry.
///
/// The manifest MUST carry an empty `[workspace]` table: without it Cargo
/// treats the nested manifest as a member of the enclosing robot workspace
/// and fails resolution before it starts ("current package believes it's in
/// a workspace when it's not") - see the regression test below. It also
/// needs a real target: a `[package]` with no target fails metadata
/// resolution before any dependency is even looked at.
pub fn write_resolve_manifest(
    project_root: &Path,
    dependencies: &[ComponentDependency],
) -> Result<PathBuf> {
    let dir = project_root.join(RESOLVE_MANIFEST_DIR_RELATIVE);
    let src_dir = dir.join("src");
    fs::create_dir_all(&src_dir)
        .with_context(|| format!("failed to create {}", src_dir.display()))?;
    fs::write(src_dir.join("lib.rs"), b"")
        .with_context(|| format!("failed to write {}", src_dir.join("lib.rs").display()))?;

    let mut deduped = dependencies.to_vec();
    deduped.sort_by(|left, right| left.catalog_id.cmp(&right.catalog_id));
    deduped.dedup();

    let mut manifest = String::new();
    manifest.push_str(
        "# Generated by phoxal-cli to resolve official component packages via `cargo\n\
         # metadata`. Rewritten on every resolve; do not edit or commit.\n\n",
    );
    manifest.push_str("[workspace]\n\n");
    manifest.push_str("[package]\n");
    manifest.push_str("name = \"phoxal-resolve\"\n");
    manifest.push_str("version = \"0.0.0\"\n");
    manifest.push_str("edition = \"2024\"\n");
    manifest.push_str("publish = false\n\n");
    manifest.push_str("[dependencies]\n");
    for dependency in &deduped {
        let package = cargo_package_name(&dependency.catalog_id);
        manifest.push_str(&format!(
            "{package} = {{ package = \"{package}\", version = \"={}\", registry = \"phoxal\" }}\n",
            dependency.train
        ));
    }

    let manifest_path = dir.join("Cargo.toml");
    fs::write(&manifest_path, manifest)
        .with_context(|| format!("failed to write {}", manifest_path.display()))?;
    Ok(manifest_path)
}

/// Resolve every direct dependency of the generated manifest at
/// `manifest_path` to its extracted package directory via `cargo metadata`,
/// keyed by Cargo package name. Follows `resolve.nodes[].deps[].pkg` ids
/// rather than matching by name, so a dependency renamed in the manifest
/// still resolves to the right package.
pub fn resolve_manifest_package_dirs(manifest_path: &Path) -> Result<BTreeMap<String, PathBuf>> {
    let metadata = run_cargo_metadata(manifest_path)?;
    let resolve = metadata
        .resolve
        .context("cargo metadata for the resolve manifest reported no resolve graph")?;
    let root_id = resolve
        .root
        .context("cargo metadata for the resolve manifest reported no root package")?;
    let root_node = resolve
        .nodes
        .iter()
        .find(|node| node.id == root_id)
        .context("cargo metadata resolve graph is missing its own root node")?;
    let packages = metadata
        .packages
        .iter()
        .map(|package| (package.id.as_str(), package))
        .collect::<BTreeMap<_, _>>();

    let mut result = BTreeMap::new();
    for dependency in &root_node.deps {
        let package = packages.get(dependency.pkg.as_str()).with_context(|| {
            format!(
                "cargo metadata resolved dependency {} to no package",
                dependency.pkg
            )
        })?;
        let manifest_dir = Path::new(&package.manifest_path)
            .parent()
            .context("resolved package manifest has no parent directory")?
            .to_path_buf();
        result.insert(package.name.clone(), manifest_dir);
    }
    Ok(result)
}

fn run_cargo_metadata(manifest_path: &Path) -> Result<Metadata> {
    let output = Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--manifest-path"])
        .arg(manifest_path)
        .arg("--config")
        .arg(registry_config_arg())
        .output()
        .context("cargo is required to resolve official component packages")?;
    if !output.status.success() {
        bail!(
            "cargo metadata failed for the generated resolve manifest {}: {}",
            manifest_path.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    serde_json::from_slice(&output.stdout)
        .context("cargo metadata returned malformed JSON for the resolve manifest")
}

#[derive(Debug, Deserialize)]
struct Metadata {
    packages: Vec<Package>,
    resolve: Option<Resolve>,
}

#[derive(Debug, Deserialize)]
struct Package {
    id: String,
    name: String,
    manifest_path: String,
}

#[derive(Debug, Deserialize)]
struct Resolve {
    root: Option<String>,
    nodes: Vec<ResolveNode>,
}

#[derive(Debug, Deserialize)]
struct ResolveNode {
    id: String,
    deps: Vec<ResolveDependency>,
}

#[derive(Debug, Deserialize)]
struct ResolveDependency {
    pkg: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// A minimal path-dependency fixture crate `component-fixture`, standing
    /// in for a published official component package: it carries a
    /// `src/lib.rs` anchor (organization#951 WS4's "Decision 4 correction")
    /// and nothing else. `write_resolve_manifest` cannot express a path
    /// dependency (real components are registry-only), so these tests hand
    /// -write the generated manifest's shape with a `path` dependency
    /// substituted for the `registry` one.
    ///
    /// The mechanism this exercises is also verified for real, against the
    /// live registry: `phoxal-component-vl53l1x@0.42.1` (`registry =
    /// "phoxal"`) resolves via `cargo metadata` exactly like this fixture
    /// does, and its extraction directory carries `component.yaml`,
    /// `simulation.yaml`, and `structure.urdf` - so the anchor-lib +
    /// generated-manifest + `resolve.nodes[].deps[].pkg` design is not just
    /// tested in isolation, it is confirmed against a published train. The
    /// path substitution here exists ONLY because unit tests must never
    /// touch the network, not because the registry path is unproven.
    fn write_fixture_dependency_crate(root: &Path) -> PathBuf {
        let dir = root.join("component-fixture");
        fs::create_dir_all(dir.join("src")).unwrap();
        fs::write(
            dir.join("Cargo.toml"),
            "[package]\nname = \"phoxal-component-fixture\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
        )
        .unwrap();
        fs::write(dir.join("src/lib.rs"), b"").unwrap();
        dir
    }

    fn write_nested_manifest(dir: &Path, with_empty_workspace_table: bool) {
        fs::create_dir_all(dir.join("src")).unwrap();
        fs::write(dir.join("src/lib.rs"), b"").unwrap();
        let mut manifest = String::new();
        if with_empty_workspace_table {
            manifest.push_str("[workspace]\n\n");
        }
        manifest.push_str(
            "[package]\nname = \"phoxal-resolve\"\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n\n\
             [dependencies]\nphoxal-component-fixture = { path = \"../../../component-fixture\" }\n",
        );
        fs::write(dir.join("Cargo.toml"), manifest).unwrap();
    }

    /// Regression for the exact failure organization#951 WS4 recorded:
    /// without the empty `[workspace]` table, Cargo treats the generated
    /// manifest as a member of the enclosing robot workspace and refuses to
    /// resolve it at all.
    #[test]
    fn missing_empty_workspace_table_is_swallowed_by_the_enclosing_workspace() {
        let root = tempfile::tempdir().unwrap();
        write_fixture_dependency_crate(root.path());
        fs::write(
            root.path().join("Cargo.toml"),
            "[workspace]\nmembers = [\"robot\"]\nresolver = \"2\"\n",
        )
        .unwrap();
        fs::create_dir_all(root.path().join("robot/src")).unwrap();
        fs::write(root.path().join("robot/src/lib.rs"), b"").unwrap();
        fs::write(
            root.path().join("robot/Cargo.toml"),
            "[package]\nname = \"robot\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
        )
        .unwrap();

        let resolve_dir = root.path().join("robot/.phoxal/resolve");
        write_nested_manifest(&resolve_dir, false);

        let error = run_cargo_metadata(&resolve_dir.join("Cargo.toml"))
            .expect_err("a nested manifest with no [workspace] table must fail resolution");
        let message = error.to_string();
        assert!(
            message.contains("believes it's in a workspace"),
            "{message}"
        );
    }

    /// With the empty `[workspace]` table `write_resolve_manifest` writes,
    /// the identical nested manifest resolves as its own root and the
    /// dependency's directory comes back correctly.
    #[test]
    fn empty_workspace_table_resolves_the_manifest_as_its_own_root() {
        let root = tempfile::tempdir().unwrap();
        let fixture_dir = write_fixture_dependency_crate(root.path());
        fs::write(
            root.path().join("Cargo.toml"),
            "[workspace]\nmembers = [\"robot\"]\nresolver = \"2\"\n",
        )
        .unwrap();
        fs::create_dir_all(root.path().join("robot/src")).unwrap();
        fs::write(root.path().join("robot/src/lib.rs"), b"").unwrap();
        fs::write(
            root.path().join("robot/Cargo.toml"),
            "[package]\nname = \"robot\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
        )
        .unwrap();

        let resolve_dir = root.path().join("robot/.phoxal/resolve");
        write_nested_manifest(&resolve_dir, true);

        let dirs = resolve_manifest_package_dirs(&resolve_dir.join("Cargo.toml"))
            .expect("an empty [workspace] table resolves the manifest as its own root");
        let resolved = dirs
            .get("phoxal-component-fixture")
            .expect("the fixture dependency resolves");
        assert_eq!(
            resolved.canonicalize().unwrap(),
            fixture_dir.canonicalize().unwrap()
        );
    }

    /// `write_resolve_manifest` itself always emits the empty `[workspace]`
    /// table and a real `src/lib.rs` target, and follows dependency ids
    /// rather than matching by name.
    #[test]
    fn write_resolve_manifest_emits_empty_workspace_table_and_anchor_target() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("robot")).unwrap();
        let manifest_path = write_resolve_manifest(
            &root.path().join("robot"),
            &[ComponentDependency {
                catalog_id: "phoxal/component-ddsm115".to_string(),
                train: "0.42.0".to_string(),
            }],
        )
        .unwrap();
        let contents = fs::read_to_string(&manifest_path).unwrap();
        assert!(contents.contains("[workspace]\n"));
        assert!(contents.contains("phoxal-component-ddsm115"));
        assert!(contents.contains("version = \"=0.42.0\""));
        assert!(manifest_path.parent().unwrap().join("src/lib.rs").is_file());
    }

    #[test]
    fn write_resolve_manifest_dedupes_repeated_dependencies() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("robot")).unwrap();
        let dependency = ComponentDependency {
            catalog_id: "phoxal/component-ddsm115".to_string(),
            train: "0.42.0".to_string(),
        };
        let manifest_path = write_resolve_manifest(
            &root.path().join("robot"),
            &[dependency.clone(), dependency],
        )
        .unwrap();
        let contents = fs::read_to_string(&manifest_path).unwrap();
        assert_eq!(contents.matches("phoxal-component-ddsm115").count(), 2);
    }
}
