[package]
name = "phoxal-cli-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = ["phoxal-internal"]

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
libc = { workspace = true }
phoxal = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sysinfo = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "process", "rt", "signal", "time"] }
tracing = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
