[package]
name = "phoxal-cli-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
object = { workspace = true }
phoxal = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
object = { workspace = true, features = ["write"] }
tempfile = { workspace = true }

[lints]
workspace = true
