name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: >-
      github.event_name != 'push' ||
      !startsWith(github.event.head_commit.message, 'chore(release): release v')
    uses: phoxal/.github/.github/workflows/rust-ci.yml@main
    secrets: inherit
