name: release-plz

on:
  push:
    branches: [main]
  schedule:
    - cron: "23 5,17 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: cli-release
  cancel-in-progress: false

jobs:
  release-plz-pr:
    name: prepare release PR
    uses: phoxal/.github/.github/workflows/rust-release-plz-pr.yml@main
    secrets: inherit
    with:
      registry-manifest-from-latest-tag: true
